apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-psql-test
  labels:
    app: my-psql-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-psql-test
  template:
    metadata:
      labels:
        app: my-psql-test
    spec:
      containers:
      - name: my-pod
        image: gcr.io/testproject-362005/mysqlv1:latest
        ports:
        - containerPort: 9803
        volumeMounts:
        - mountPath: /opt
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: myclaim