pipeline {
    agent any


    environment {
    SVC_ACCOUNT_KEY = credentials('tf-auth')
  }
     
    stages {
        stage ('checkout'){
            steps {
                git branch: 'gcp-terraform', url: 'https://github.com/ksv077/mytest.git'
            }
        }
      

		stage('Set Terraform path') {
            steps {
                //script {
                    //def tfHome = tool name: 'Terraform'
                    //withEnv(["PATH=/usr/local/bin:$env.PATH"])
		    sh '''
		    cd /usr/local/bin
		    terraform init
		    '''
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./VM-VPC/terraform.json'
		sh 'pwd'
                sh 'terraform --version'               
               
            }
        }
        
         stage('Initialize Terraform') {
		 steps {  
			  dir('VM-VPC')
			 {
                sh 'terraform init'
			 }
		 }
	 }
				  
	stage('Terraform Action') {
		 steps {  
			  dir('VM-VPC')
			 {
                sh 'terraform $TF_ACTION $TF_APPROVE'
				 //sh 'terraform plan'
				 //sh 'terraform destroy --auto-approve'
			 }
		 }
	}
                             
}
}
