pipeline {
    agent any


    environment {
    SVC_ACCOUNT_KEY = credentials('tf-auth')
  }
     
    stages {
        stage ('checkout'){
            steps {
                git branch: 'gcp-terraform', url: 'https://github.com/ksv077/mytest.git'
            }
        }
      

		stage('Set Terraform path') {
            steps {
                script {
                    def tfHome = tool name: 'terraform'
                    env.PATH = "${tfHome}:${env.PATH}"
                }
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./VM-VPC/terraform.json'
		sh 'pwd'
                sh 'terraform --version'               
               
            }
        }
        
         stage('Initialize Terraform') {
		 steps {  
			  dir('VM-VPC')
			 {
                sh 'terraform init'
			 }
		 }
	 }
				  
	stage('Terraform Action') {
		 steps {  
			  dir('VM-VPC')
			 {
                //sh 'terraform $TF_ACTION $TF_APPROVE'
				 //sh 'terraform plan'
				 sh 'terraform apply --auto-approve'
			 }
		 }
	}
                             
}
}
